### ISSUE TITLE
Bug: false positive error reporting

### ISSUE THREAD

**Issue by juh9870** [ayecue/miniscript-vs#24]
The bug can be observed in the MiniMicro sysdisk

https://github.com/JoeStrout/minimicro-sysdisk/blob/615a530843359e289d595c704182f9094d7e0beb/sys/lib/spriteControllers.ms#L258

![image](https://github.com/ayecue/miniscript-vs/assets/15922601/f0f017b5-586b-4ed4-a61d-3936c661b3f4)

**Comment by ayecue** [comment]
Which version of miniscript-vs are you using? Seems to parse fine for me without showing any errors.

**Comment by juh9870** [comment]
Yeah, sorry, my version was horribly outdated (I forgot to update nixos config), it is fine in the 0.5.2
